from fpdf import FPDF
from datetime import datetime


def generate_report(df):

    pdf = FPDF()
    pdf.add_page()

    # -----------------------------
    # Title
    # -----------------------------
    pdf.set_font("Arial", "B", 18)
    pdf.cell(
        0,
        10,
        "InsightGPT Lite Report",
        ln=True,
        align="C"
    )

    pdf.ln(10)

    # -----------------------------
    # Project Information
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        0,
        10,
        "Project Information",
        ln=True
    )

    pdf.set_font("Arial", size=12)

    pdf.multi_cell(
        0,
        8,
        "InsightGPT Lite: An AI-Powered Data Analytics and Retrieval-Augmented Query Platform"
    )

    pdf.ln(5)

    # -----------------------------
    # Dataset Summary
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        0,
        10,
        "Dataset Summary",
        ln=True
    )

    pdf.set_font("Arial", size=12)

    pdf.cell(
        0,
        8,
        f"Rows: {df.shape[0]}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Columns: {df.shape[1]}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Missing Values: {df.isnull().sum().sum()}",
        ln=True
    )

    pdf.ln(5)

    # -----------------------------
    # Column Names
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        0,
        10,
        "Columns in Dataset",
        ln=True
    )

    pdf.set_font("Arial", size=12)

    for column in df.columns:
        pdf.cell(
            0,
            8,
            f"- {column}",
            ln=True
        )

    pdf.ln(5)

    # -----------------------------
    # Data Types
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        0,
        10,
        "Column Data Types",
        ln=True
    )

    pdf.set_font("Arial", size=12)

    for column in df.columns:
        dtype = str(df[column].dtype)

        pdf.cell(
            0,
            8,
            f"{column}: {dtype}",
            ln=True
        )

    pdf.ln(5)

    # -----------------------------
    # Report Generation Details
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        0,
        10,
        "Report Details",
        ln=True
    )

    pdf.set_font("Arial", size=12)

    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    pdf.cell(
        0,
        8,
        f"Generated On: {current_time}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        "Generated By: InsightGPT Lite",
        ln=True
    )

    pdf.cell(
        0,
        8,
        "Platform: AI-Powered Data Analytics and RAG System",
        ln=True
    )

    # -----------------------------
    # Save PDF
    # -----------------------------
    report_path = "reports/InsightGPT_Report.pdf"

    pdf.output(report_path)

    return report_path